# https://github.com/elastic/kibana-docker
FROM httpd:2.4

COPY .htaccess /home/.htaccess
#COPY enhanced_tilemap-master.zip /tmp/enhanced_tilemap-master.zip

#RUN kibana-plugin install https://github.com/nreese/enhanced_tilemap/releases/download/v2017-04-19/enhanced-tilemap-v2017-04-19-5.3.0.zip
#RUN kibana-plugin install  path:///tmp/enchanced_tilemap-mster.zip

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
